version: '3'

services:
  user-svc-db:
    image: docker.io/bitnami/postgresql:15
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_USERNAME=root'
      - 'POSTGRESQL_PASSWORD=root'
      - 'POSTGRESQL_DATABASE=user_svc'
      - 'POSTGRESQL_PORT_NUMBER=5432'

volumes:
  pgdata:
    driver: local